site_name: Dokumentacja NASweb
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: pl
  favicon: favicon.png
  logo: image.png
  palette:
    primary: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Start: 
    - index.md
  - Informacje techniczne:
    - Home.md
    - NASweb-polski.md
    - NASweb-english.md
  - Aplikacja:
    - Aplikacja/index.md
    - Aplikacja/Logowanie.md
    - Panel: 
      - Aplikacja/Panel/Pulpit.md
      - Aplikacja/Panel/Urzadzenie.md
      - Aplikacja/Panel/Monitor-zdarzen.md

      - Kontrola dostępu:
        - Aplikacja/Panel/KD/Uzytkownicy.md
        - Aplikacja/Panel/KD/Karty.md
        - Aplikacja/Panel/KD/Wzorce-uprawnien.md
        - Aplikacja/Panel/KD/Przejscia-i-Czytniki.md

      - SSWiN:
        - Aplikacja/SSWiN/Strefy.md
        - Aplikacja/SSWiN/Wejscia.md
        - Aplikacja/SSWiN/Wyjscia-przypisane-do-strefy.md

      - Aplikacja/Panel/Wideorejestracja.md
      - Aplikacja/Panel/Status.md

      - Ustawienia:
        - Ustawienia/Pulpit.md
        - Ustawienia/GSM.md
        - Ustawienia/Wejscia.md
        - Ustawienia/CMS.md
        - Ustawienia/Email.md
        - Ustawienia/Konfiguracja-formatu-kart.md
        - Ustawienia/Kamery.md
        - Ustawienia/Campics.md
        - Ustawienia/Powiadomienia.md
        - Ustawienia/Linki-zewnetrzne.md
        
      - Skrypty:
        - Aplikacja/Panel/Skrypty/Pliki-skryptow.md
        - Aplikacja/Panel/Skrypty/Filtry-skryptow.md
        - Aplikacja/Panel/Skrypty/Logi-skryptow.md

      - Aplikacja/Panel/Admin.md

    - Opcje dodatkowe:
      - Aplikacja/Panel/Uzytkownicy/Edycja.md
      - Aplikacja/Panel/Uzytkownicy/Tworzenie-nowego.md
      - Aplikacja/Panel/Uzytkownicy/Menu-szybkiej-zmiany.md

  - Kontroler:
    - Kontroler/index.md
  - Home Assistant:
    - HomeAssistant/Home-Assistant-Operating-System.md
    - HomeAssistant/Instalacja-integracji.md
  - Dodatki:
    - Dodatki/index.md
    - Dodatki/Tworzenie_powiadomienia.md
    - Dodatki/Tworzenie-skryptu.md
    - Dodatki/Dodanie-nowej-karty.md
    - Dodatki/Dodanie-Campics.md
    - Dodatki/Dodanie-zewnetrznej-aplikacji.md
  - FAQ:
    - FAQ/index.md
    - FAQ/NASwebio.md
    - FAQ/NASweb.md